timeout: 3
interface_branding: FacetOS - choose how to start
interface_branding_colour: 6
interface_help_hidden: yes

/FacetOS 1.3
    protocol: multiboot2
    path: boot():/boot/facetos.elf

/FacetOS 1.3 (Safe mode)
    protocol: multiboot2
    path: boot():/boot/facetos.elf
    cmdline: safe
    resolution: 1024x768
